name: metrics

services:
  postgres:
    image: quay.io/fedora/postgresql-15
    container_name: postgres
    user: postgres
    volumes:
      - ./container/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
